server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Obsługa ścieżki /sixfit
    location /sixfit/ {
        try_files $uri $uri/ /sixfit/index.html;
    }

    location = /sixfit {
        return 301 $scheme://$http_host$uri/;
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml;
}